version: "3"

tasks:
  start:
    desc: Setups up the xampp dev environment
    cmds:
      - docker compose -f config/docker-compose.yml --env-file config/.env -p xampp-dev up -d
    
  remove:
    desc: Setups up the xampp dev environment
    cmds:
      - docker-compose -f config/docker-compose.yml --env-file config/.env -p xampp-dev down