version: "3"

services:
  www:
    build: .
    restart: unless-stopped
    ports: 
      - '${WEB_PORT}:80'
    volumes:
      - ../www:/var/www/html/
    links:
      - db
    networks:
      - default

  db:
    image: mariadb
    restart: unless-stopped
    ports: 
      - '${DATABASE_PORT}:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../dump:/docker-entrypoint-initdb.d
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links: 
      - db:db
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}